//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baptism
    {
        public int Id { get; set; }
        public string BapitsmNumber { get; set; }
        public string BaptismPlace { get; set; }
        public System.DateTime BaptismDate { get; set; }
        public string BaptismName { get; set; }
        public string Othername { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string HomeTown { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public int BaptismType { get; set; }
        public string NameOfGodParent1 { get; set; }
        public string NameOfGodParent2 { get; set; }
        public string NameOfMinister { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MemberId { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
