//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberFamilyMetaDatas = new HashSet<MemberFamilyMetaData>();
            this.SocietyMemberLinks = new HashSet<SocietyMemberLink>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othername { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int Gender { get; set; }
        public string HomeParish { get; set; }
        public string Town { get; set; }
        public string Nationality { get; set; }
        public string Phone2 { get; set; }
        public string EmploymentAddress { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string NextOfKin { get; set; }
        public string NextOfKinAddress { get; set; }
        public Nullable<int> NextOfKinMaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpousePhone { get; set; }
        public string SpousePhone2 { get; set; }
        public Nullable<int> FamilyMaleSize { get; set; }
        public Nullable<int> FamilyFemaleSize { get; set; }
        public Nullable<int> StatutoryGroup { get; set; }
        public Nullable<int> MembershipType { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public int Confirmed { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmedBy { get; set; }
        public string PassportUrl { get; set; }
        public int Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int Deceased { get; set; }
        public Nullable<System.DateTime> DateDeceased { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> Station { get; set; }
    
        public virtual LookUpTable LookUpTable { get; set; }
        public virtual LookUpTable LookUpTable1 { get; set; }
        public virtual LookUpTable LookUpTable2 { get; set; }
        public virtual LookUpTable LookUpTable3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberFamilyMetaData> MemberFamilyMetaDatas { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocietyMemberLink> SocietyMemberLinks { get; set; }
    }
}
