//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.SocietyMemberLinks = new HashSet<SocietyMemberLink>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othername { get; set; }
        public string Phone { get; set; }
        public Nullable<int> MembershipType { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public int Confirmed { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmedBy { get; set; }
        public string PassportUrl { get; set; }
        public int Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int Deceased { get; set; }
        public Nullable<System.DateTime> DateDeceased { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocietyMemberLink> SocietyMemberLinks { get; set; }
    }
}
