//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reflection
    {
        public int Id { get; set; }
        public string Reflection1 { get; set; }
        public string ReflectionAuthor { get; set; }
        public int ReflectionType { get; set; }
        public System.DateTime ReflectionDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int DeleteFlag { get; set; }
    }
}
