//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SacramentMemberLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SacramentMemberLink()
        {
            this.SacramentMemberUpdateLogs = new HashSet<SacramentMemberUpdateLog>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int SacramentId { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string RecordedBy { get; set; }
        public int Deleted { get; set; }
    
        public virtual Sacrament Sacrament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SacramentMemberUpdateLog> SacramentMemberUpdateLogs { get; set; }
    }
}
