//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyMemberLink
    {
        public int Id { get; set; }
        public int SocietyId { get; set; }
        public int MemberId { get; set; }
        public int MemberPositionId { get; set; }
        public System.DateTime AppointDate { get; set; }
        public int Active { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Society Society { get; set; }
        public virtual Member Member { get; set; }
    }
}
