//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StFrancisCCEntities : DbContext
    {
        public StFrancisCCEntities()
            : base("name=StFrancisCCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LookUpTable> LookUpTables { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<ParishEvent> ParishEvents { get; set; }
        public virtual DbSet<ParishEventType> ParishEventTypes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Sacrament> Sacraments { get; set; }
        public virtual DbSet<SacramentDetail> SacramentDetails { get; set; }
        public virtual DbSet<SacramentMemberLink> SacramentMemberLinks { get; set; }
        public virtual DbSet<SacramentMemberUpdateLog> SacramentMemberUpdateLogs { get; set; }
        public virtual DbSet<Society> Societies { get; set; }
        public virtual DbSet<SocietyMemberLink> SocietyMemberLinks { get; set; }
        public virtual DbSet<StationEvent> StationEvents { get; set; }
        public virtual DbSet<Reflection> Reflections { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Baptism> Baptism { get; set; }
        public virtual DbSet<Communion> Communions { get; set; }
        public virtual DbSet<Confirmation> Confirmations { get; set; }
        public virtual DbSet<Matrimony> Matrimonies { get; set; }
    }
}
