//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessObject.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklySchedule
    {
        public int Id { get; set; }
        public int DayOfTheWeek { get; set; }
        public string Time { get; set; }
        public string Description { get; set; }
        public int ScheduleType { get; set; }
        public int Station { get; set; }
    
        public virtual Station Station1 { get; set; }
    }
}
